dnf install \
    acpi \
    alacritty \
    autojump \
    autojump-zsh \
    calc \
    chromium \
    clang \
    dunst \
    ffmpeg-free \
    fish \
    fzf \
    git \
    grim \
    kitty \
    libavcodec-freeworld \
    mpv \
    network-manager-applet \
    openssl \
    openssl-devel \
    pavucontrol \
    python3 \
    slurp \
    sway \
    swaybg \
    swayidle \
    waybar \
    wdisplays \
    wf-recorder \
    wofi \
    wl-clipboard \
    zsh
